// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmSh0u85UG6bNlfaP3yKPn1SpKLtZctw0',
    appId: '1:45261307866:web:dd733e5a1cd1b9dfcecae3',
    messagingSenderId: '45261307866',
    projectId: 'geofenceat',
    authDomain: 'geofenceat.firebaseapp.com',
    databaseURL: 'https://geofenceat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geofenceat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOb1c7DCouximm9yiiDdFrgNz_b5_bnI8',
    appId: '1:45261307866:android:83ea07ef2e4bb3b5cecae3',
    messagingSenderId: '45261307866',
    projectId: 'geofenceat',
    databaseURL: 'https://geofenceat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geofenceat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzq9zgVdSwOXfT5qBa4odv-kW_7bEhj-Q',
    appId: '1:45261307866:ios:36a898798743d430cecae3',
    messagingSenderId: '45261307866',
    projectId: 'geofenceat',
    databaseURL: 'https://geofenceat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geofenceat.firebasestorage.app',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzq9zgVdSwOXfT5qBa4odv-kW_7bEhj-Q',
    appId: '1:45261307866:ios:36a898798743d430cecae3',
    messagingSenderId: '45261307866',
    projectId: 'geofenceat',
    databaseURL: 'https://geofenceat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geofenceat.firebasestorage.app',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmSh0u85UG6bNlfaP3yKPn1SpKLtZctw0',
    appId: '1:45261307866:web:b8f77dadaa5de68acecae3',
    messagingSenderId: '45261307866',
    projectId: 'geofenceat',
    authDomain: 'geofenceat.firebaseapp.com',
    databaseURL: 'https://geofenceat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geofenceat.firebasestorage.app',
  );
}
